### ISSUE TITLE
Could Kashgari model which inherits from Keras be converted to onnx model?

### ISSUE THREAD

**Issue by Igoslow** [onnx/onnx-docker#57]
import onnxmltools
from keras.models import load_model
import kashgari
input_keras_model = 'E:\KG\kashgari/train\gonghang_2020_12_10'

# Change this path to the output name and path for the ONNX model
output_onnx_model = 'kashgari_model.onnx'

# Load your Keras model
loaded_model = kashgari.utils.load_model(input_keras_model)

onnx_model = onnxmltools.convert_keras(loaded_model.tf_model)

# Save as protobuf
onnxmltools.utils.save_model(onnx_model, output_onnx_model)

This is a bug as follows:
ValueError: Input 0 of node TFNodes50/Embedding-Token/embedding_lookup was passed float from TFNodes50/Embedding-Token/embeddings:0 incompatible with expected resource.

Process finished with exit code 1

**Comment by Igoslow** [comment]
this is a bug as follows:
Traceback (most recent call last):
  File "E:/KG/kashgari/test_kashgari_onnx.py", line 26, in <module>
    onnx_model = onnxmltools.convert_keras(loaded_model.tf_model)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\onnxmltools\convert\main.py", line 33, in convert_keras
    return convert(model, name, doc_string, target_opset, channel_first_inputs)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\keras2onnx\main.py", line 82, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\keras2onnx\parser.py", line 828, in parse_graph
    return _parse_graph_core(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\keras2onnx\parser.py", line 746, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\keras2onnx\parser.py", line 402, in _on_parsing_tf_subgraph
    subgraph, replacement = create_subgraph(graph, node_list, sess, operator.full_name)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\keras2onnx\subgraph.py", line 170, in create_subgraph
    tf.import_graph_def(output_graph_def, name=im_scope)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\tensorflow_core\python\framework\importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "C:\Users\Learn\Envs\jiansuo1\lib\site-packages\tensorflow_core\python\framework\importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node TFNodes50/Embedding-Token/embedding_lookup was passed float from TFNodes50/Embedding-Token/embeddings:0 incompatible with expected resource.

Process finished with exit code 1

**Comment by jiafatom** [comment]
Please try keras2onnx master directly to see if it works.
